#!/bin/sh
sql=$(ssh root@idmy.team -p 2222 'export PYTHONPATH=/var/www/settings/:$PYTHONPATH && cd /var/www/ && python helpers/dump_schema.py')
echo "$sql" > 'db/schema.sql'

$(which python) helpers/gen_yaml_confs.py
echo $?