repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable' ]
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: uncreated migrations
        entry: ./web/manage.py makemigrations --check --dry-run
        pass_filenames: false
