language: python

python:
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install opencv-python

script: pytest

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test-idmyteam;' # matches env

env:
  - DB_PASSWORD=''
  - DB_USERNAME=root
  - DB_TABLE=test-idmyteam