language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install opencv-python

cache: pip

script: pytest

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test-idmyteam;' # matches env

env:
  global:
    - DB_PASSWORD=''
    - DB_USERNAME=root
    - DB_TABLE=test-idmyteam