language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install opencv-python

cache: pip

script: python3 -m pytest tests/ -m "not rpi"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `test-idmyteam`;' # matches env

env:
  global:
    - TEST_DB_PASSWORD=''
    - TEST_DB_USERNAME=root
    - TEST_DB_TABLE=test-idmyteam
    - ROOT_DIR=${TRAVIS_BUILD_DIR}
    - PYTHONPATH=${TRAVIS_BUILD_DIR}/settings/:${TRAVIS_BUILD_DIR}/web/:$PYTHONPATH