language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install opencv-python

cache: pip

script: python3 -m pytest tests/ -m "not rpi"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `idmyteam-client-test`;' # matches env
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('VWpyKKUGaFZQIiCj680n') WHERE user='idmyteamtest';\nFLUSH PRIVILEGES;\n" | mysql -u root

env:
  global:
    - SETTINGS_FILE=${TRAVIS_BUILD_DIR}/conf/test_local.yaml
    - PYTHONPATH=${TRAVIS_BUILD_DIR}/settings/:${TRAVIS_BUILD_DIR}/web/:$PYTHONPATH