version: "2"
services:
  app:
    build: .
    links:
      - db
    restart: always
    network_mode: "host"

  db:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=idmyteam
      - MYSQL_USER=idmyteam
      - MYSQL_PASSWORD=idmyteam

  migrate:
    image: migrate/migrate
    network_mode: "host"
    volumes:
      - ./sql:/migrations
    command: ["-path", "/migrations/", "-database", "mysql://idmyteam:idmyteam@tcp(127.0.0.1:3306)/idmyteam", "up"]