<?php
/* script moves user from tmp directory (when taking photos) to classified directory */
session_start();
require '../../functions.php';
handlePagePermission("medium");
$member_id = $_SESSION['training_member_id'] or ESC("/members", "No session");

// make the actual classification directory if not exists
mdir("${classified_dir}${member_id}");

// get coordinates of image from the sessions generated by
// faces-selector/store-coordinates.php and store in image file as comment
foreach($_SESSION['coords'] as $image_path => $coord){
    if(!file_exists($image_path)) continue;
    $img_coords = $_SESSION['coords'][$image_path];
    if(!validCoords($img_coords)) continue;
    if(!storeImageComment($image_path, $img_coords)) ESC("/members", "Unable to store face location");
}

// move tmp images to the classified directory
$images = glob("${tmp_classified_dir}${member_id}/*${IMG_TYPE}");
//if(count($images) == 0) ESC("/member/train", "No new images to send to training! Updated coordinates if changed.");
foreach ($images as $image_path) {
    // make sure image being sent to classification has face coords
    if(!validCoords(getImageComment($image_path))) ESC("/member/train", "Not every image has face coordinates selected!");

    // move image to pending classified dir
    $image_name = str_replace($tmp_classified_dir, "", $image_path); // remove directory
    rename($image_path,"${classified_dir}${image_name}");
}

//remove tmp directory of camera captures
rmdir("${tmp_classified_dir}${member_id}");

// delete training_member session
unset($_SESSION['coords']);
unset($_SESSION['training_member_id']);

// upload classified images
$cmd = escapeshellcmd("sudo '$upload_classifications_script'");
$output = shell_exec($cmd);

// wait for python script to mark members as training (flashing faces)
sleep(4);

ESC("/members", false, "Success setting up member. Remember to turn off Silent Mode in Settings to start recognitions.");