#!/bin/sh

sql=$(ssh root@idmy.team -p 2222 'export PYTHONPATH=/var/www/settings/:$PYTHONPATH && cd /var/www/ && python helpers/dump_schema.py')
echo "$sql" > 'db/schema.sql'

export ROOT='$(pwd)'
export PYTHONPATH="$(pwd):$(pwd)web:$(pwd)settings:$(pwd)helpers"
eval "$(which python3) $(which pytest)"

exit -1
