# Generated by Django 3.1.2 on 2020-11-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idmyteamclient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="permission",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Phantom Member"),
                    (1, "Low Member"),
                    (2, "Medium Member"),
                    (3, "High Member"),
                ]
            ),
        ),
    ]
