name: ID My Team Client
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: a8r(%ir&!=7rc0ycu(=fwks1qc$#lsr34_5p7v+dbif7kh%1pn
      DJANGO_SETTINGS_MODULE: web.settings
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements for web
        run: |
          pip install --upgrade pip
          cd web
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - uses: pre-commit/action@v2.0.0

      - name: Test web
        run: |
          cd web
          cp init_settings.yaml settings.yaml
          pytest --cov=./ --cov-report=xml

      - name: Upload web coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./web/coverage.xml
